def gv

pipeline {
  agent any
     
   environment {
        registryName = "defsloc/advisingbank"
        registryCredential = 'ACR'
        dockerImage = ''
        registryUrl = 'defsloc.azurecr.io'
    }
    
    stages {
        stage("init") {
            steps {
                script {
                    sh "ls -la"
                    sh "pwd"
                    sh "whoami"
                    sh "ls -la /target/"
                    gv = load "jenkins/script.groovy"
                }
            }
        }
        stage("build jar") {
            steps {
                script {
                    echo "building jar"
                    gv.buildJar()
                }
            }
        }
        stage("build image") {
            steps {
                script {
                    echo "building image"
                    gv.buildImage()
                }
            }
        }
        
        // Uploading Docker images into ACR
    stage('Upload Image to ACR') {
     steps{   
         script {
             echo "Pushing Build image into ACR"
             gv.pushImage()
        }
      }
    }
  
    stage('Docker Run') {
     steps{
         script {
            gv.runImage()
            }
      }
    }
        stage("deploy") {
            steps {
                script {
                    echo "deploying"
                    gv.deployApp()
                }
            }
        }
    }   
}
