def gv

pipeline {
  agent any
     
   environment {
        registryName = "maven-registry"
        registryCredential = 'ACR'
        dockerImage = ''
        registryUrl = 'defsloc.azurecr.io'
    }
    
    stages {
        stage("init") {
            steps {
                script {
                    sh "ls -la"
                    sh "pwd"
                    sh "whoami"
                    sh "ls -la target/"
                    gv = load "jenkins/script.groovy"
                }
            }
        }
      
        stage("Build jar") {
            steps {
                script {
                    echo "building jar"
                    gv.buildJar()
                }
            }
        }

        stage('Generate Junit Test Report') {
            steps {
              script {
                    echo "generating report"
                    gv.testReport()
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
      
        stage("Build Image") {
            steps {
                script {
                    echo "building image"
                    gv.buildImage()
                }
            }
        }
      
        
        // Uploading Docker images into ACR
        stage('Upload Image to ACR') {
         steps{   
             script {
                 echo "Pushing Build image into ACR"
                 gv.pushImage()
            }
          }
        }
      
        // Stopping Docker containers for cleaner Docker run
         stage('Stop Previous Containers') {
             steps {
               script {
                gv.destroy()
                }
             }
           }

        stage('Docker Run') {
         steps{
             script {
                gv.runImage()
                }
             }
         }
      
        stage('Remove Unused docker image') {
           steps{
             script {
                gv.deleteImage()
              }
           }
        }
      
        stage("Deploy to Environment") {
            steps {
                script {
                    echo "deploying"
                    gv.deployApp()
                }
            }
        }
    }   
}
